volumes:
    dockerdb:
services:
  web:
    build: .
    ports:
      - 80:80
    container_name: razortodowebapp
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: P@ssw0rd
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqledgedb
    ports:
      - 1433:1433
    extra_hosts: 
      - host.docker.internal:host-gateway
    volumes:
      - dockerdb:/home/node/app

    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s     
         
       